name: DevSecOps Pipeline

on: [push, pull_request]

jobs:
  security-analysis:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: auth
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache OWASP Data
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/odc-data
          key: ${{ runner.os }}-odc-data-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-odc-data-

      - name: SAST - Semgrep Scan
        run: |
          pip install semgrep
          semgrep scan --config auto --error

      - name: SCA - Dependency Check
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/src:z \
            -v ${{ github.workspace }}/odc-data:/usr/share/dependency-check/data:z \
            owasp/dependency-check-action:latest \
            --project "MyProject" \
            --scan /src \
            --format "HTML" \
            --disableAssembly \
            --enableExperimental \
            --nvdApiKey ${{ secrets.NVD_API_KEY }} \
            --failOnCVSS 7

      - name: DAST - OWASP ZAP Scan
        run: |
          chmod +x ./gradlew
          ./gradlew :AuthService:bootRun > server.log 2>&1 &
          
          echo "Ожидание запуска приложения на порту 8081..."
          
          TIMEOUT=60
          while ! nc -z localhost 8081; do   
            sleep 2
            TIMEOUT=$((TIMEOUT - 2))
            if [ $TIMEOUT -le 0 ]; then
              echo "Приложение не запустилось за отведенное время! Логи запуска:"
              cat server.log
              exit 1
            fi
          done
          
          echo "Приложение успешно запущено и слушает порт 8081!"

          docker run --network="host" -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t http://localhost:8081 \
            -g gen.conf \
            -r report.html || true
          
          pkill -f bootRun
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            dependency-check-report.html
            report.html