spring.application.name=EmployeeService

spring.datasource.url=jdbc:postgresql://localhost:5432/employee
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

randomuser.api.url=https://randomuser.me/api/
scheduler.outbox-fixed-delay=500
scheduler.cron=0 0 1 * * *

kafka.topic.employee-data=employee.service.employeeData
spring.kafka.bootstrap-servers=localhost:9092

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=3600000

server.port=8082
